apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  APP_PORT:             {{ .Values.app.port | quote }}
  APP_ENV:              {{ .Values.app.env | quote }}
  {{- if .Values.postgresql.enabled }}
  DB_HOST:              {{ printf "%s-postgresql" .Values.name | quote }}
  {{- else }}
  DB_HOST:              {{ .Values.db.host | quote }}
  {{- end }}
  DB_PORT:              {{ .Values.db.port | quote }}
  DB_USER:              {{ .Values.db.user | quote }}
  DB_NAME:              {{ .Values.db.name | quote }}
  DB_SSLMODE:           {{ .Values.db.sslmode | quote }}
  K8S_NAMESPACE_PREFIX: {{ .Values.k8s.namespacePrefix | quote }}
  VAULT_ADDR:           {{ .Values.vault.addr | quote }}
  VAULT_VTA_ADDR:       {{ .Values.vault.vtaAddr | default .Values.vault.addr | quote }}
  VAULT_KV_MOUNT:       {{ .Values.vault.kvMount | quote }}
  VAULT_K8S_AUTH_MOUNT: {{ .Values.vault.k8sAuthMount | quote }}
  VAULT_APPROLE_MOUNT:  {{ .Values.vault.appRoleMount | quote }}
  VAULT_MEDIATOR_TOKEN_ROLE: {{ .Values.vault.mediatorTokenRole | quote }}
  VAULT_SKIP_VERIFY:    {{ .Values.vault.skipVerify | quote }}
  CLUSTER_DOMAIN:       {{ .Values.cluster.domain | quote }}
  GITHUB_PACKAGE_OWNER:      {{ .Values.github.packageOwner | quote }}
  GITHUB_PACKAGE_NAME:       {{ .Values.github.packageName | quote }}
  GITHUB_MEDIATOR_PACKAGE_NAME: {{ .Values.github.mediatorPackageName | quote }}
  GITHUB_DID_HOSTING_DAEMON_PACKAGE_NAME: {{ .Values.github.didHostingDaemonPackageName | quote }}
  WEBAUTHN_RP_ID:            {{ .Values.webauthn.rpID | quote }}
  WEBAUTHN_RP_ORIGINS:       {{ .Values.webauthn.rpOrigins | quote }}
  WEBAUTHN_RP_DISPLAY_NAME:  {{ .Values.webauthn.rpDisplayName | quote }}
