package handler

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
)

// GrantSessionAdmin — POST /api/v1/setup/:id/admins (user only).
//
// Adds another PNM's did:key as an unrestricted administrator on a running
// VTA. userSession scopes the lookup to the authenticated owner; this route
// can never grant access on another user's agent or on the passkey-less
// platform stack.
//
// The operation is synchronous and briefly stops the VTA because its ACL store
// is held under an exclusive lock by the running process. The shared snapshot
// maintenance lock prevents overlapping work across API replicas.
func (h *SetupHandler) GrantSessionAdmin(c *gin.Context) {
	session := h.userSession(c)
	if session == nil {
		return
	}
	if session.Status != "running" {
		c.JSON(http.StatusConflict, gin.H{"error": "session must be in running status"})
		return
	}

	var body struct {
		AdminDid string `json:"admin_did" binding:"required"`
	}
	if err := c.ShouldBindJSON(&body); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "admin_did is required"})
		return
	}

	did := strings.TrimSpace(body.AdminDid)
	if !didKeyRe.MatchString(did) {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": "admin_did must be a did:key generated by PNM",
		})
		return
	}

	h.grantVtaAdmin(c, session, did, additionalPnmLabel(did), "session owner")
}

// PNM rotates away from the submitted DID on first connect, so the ACL entry
// needs a stable label. The UI intentionally asks for only the recovery DID;
// retaining a short suffix keeps multiple backup PNMs distinguishable later at
// a `pnm acl list` prompt without collecting another piece of user input.
func additionalPnmLabel(did string) string {
	const suffixLength = 10
	suffix := did
	if len(suffix) > suffixLength {
		suffix = suffix[len(suffix)-suffixLength:]
	}
	return "pnm-backup-" + suffix
}
