package didhosting

import (
	"fmt"
	"strings"
	"sync"
)

// Factory builds a Client for whichever DID-hosting control API a given session
// was provisioned against.
//
// The client used to be a startup singleton, built from DID_HOSTING_CONTROL_URL.
// That could not survive the control URL becoming a per-session value: the
// platform stack whose daemon every vta_only session uploads to does not exist
// on first boot, its URL changes when it is rebuilt, and a session torn down
// later has to be deleted from the daemon it was actually uploaded to rather
// than whatever is current.
//
// What stays global is the keypair. It is vtafarm-api's OWN identity —
// generated by `make gen-keypair` and enrolled in a daemon's ACL with
// role=admin — not anything the daemon issued, so it is the same credential
// whichever host it authenticates against. See docs/vta-setup-design.md for
// the open question of how it reaches a user-supplied daemon's ACL.
type Factory struct {
	clientDid  string
	privKeyB64 string

	mu     sync.Mutex
	byBase map[string]*Client
}

// NewFactory returns nil when the keypair is unset, matching the old behaviour
// where an unconfigured DID_HOSTING_DID/PRIVATE_KEY disabled auto-upload
// altogether — callers already treat a nil client as "hosting not configured".
func NewFactory(clientDid, privKeyB64 string) *Factory {
	if clientDid == "" || privKeyB64 == "" {
		return nil
	}
	return &Factory{clientDid: clientDid, privKeyB64: privKeyB64, byBase: map[string]*Client{}}
}

// ClientDid is the DID that has to be present in a daemon's ACL for anything
// this factory builds to authenticate. Exposed so the platform stack's pipeline
// can enroll it offline while provisioning that daemon, rather than leaving an
// operator to do it by hand.
func (f *Factory) ClientDid() string {
	if f == nil {
		return ""
	}
	return f.clientDid
}

// For returns a Client for controlURL, reusing one already built for that URL.
//
// Caching is not just to save a round trip: New fetches the server's DID from
// /api/server-info, so an uncached call reaches the network on every upload,
// ACL write and teardown. Clients are keyed by URL and hold no per-session
// state, so sharing one is safe.
//
// expectedServerDid, when non-empty, is the DID the caller already knows this
// daemon to have — see checkAudience for why that matters. Empty means "no
// expectation on record", which is the state of every vta_only session until
// its did_hosting_did column is populated.
func (f *Factory) For(controlURL, expectedServerDid string) (*Client, error) {
	if f == nil {
		return nil, fmt.Errorf("DID hosting not configured (no client keypair)")
	}
	base := strings.TrimRight(controlURL, "/")
	if base == "" {
		return nil, fmt.Errorf("session has no DID hosting control URL")
	}

	f.mu.Lock()
	defer f.mu.Unlock()
	if c, ok := f.byBase[base]; ok {
		return c, checkAudience(base, c.serverDid, expectedServerDid)
	}
	c, err := New(base, f.clientDid, f.privKeyB64)
	if err != nil {
		// Deliberately not cached: /api/server-info failing is usually a daemon
		// that is not up yet, and the next attempt should retry rather than
		// inherit the failure.
		return nil, err
	}
	// Cached before the audience check, and the error returned alongside the
	// cached entry above: a mismatch says the CALLER's expectation is wrong for
	// this URL, not that the client is unusable. A later call carrying the right
	// expectation must hit the cache and succeed rather than re-fetching.
	f.byBase[base] = c
	return c, checkAudience(base, c.serverDid, expectedServerDid)
}

// checkAudience refuses a daemon whose self-reported DID is not the one we
// expected to be talking to.
//
// serverDid comes from the daemon's own /api/server-info and becomes the `aud`
// of every id_token this client signs — with vtafarm-api's private key, which
// holds an admin ACL entry on every daemon the farm operates. A host that
// answers with somebody else's DID therefore receives a token minted for that
// somebody else, and can replay it there as us.
//
// Nothing has needed this while control URLs came only out of our own database
// and named daemons we provisioned. It is written down now because the moment a
// session can be pointed at a daemon on the strength of a value a user handed
// us, "the daemon says who it is" stops being a safe answer to "who am I
// signing for".
func checkAudience(base, serverDid, expected string) error {
	if expected == "" || serverDid == expected {
		return nil
	}
	return fmt.Errorf("DID hosting daemon at %s reports server DID %q, expected %q", base, serverDid, expected)
}
