package didhosting

import (
	"fmt"
	"strings"
	"sync"
)

// Factory builds a Client for whichever DID-hosting control API a given session
// was provisioned against.
//
// The client used to be a startup singleton, built from DID_HOSTING_CONTROL_URL.
// That could not survive the control URL becoming a per-session value: the
// platform stack whose daemon every vta_only session uploads to does not exist
// on first boot, its URL changes when it is rebuilt, and a session torn down
// later has to be deleted from the daemon it was actually uploaded to rather
// than whatever is current.
//
// What stays global is the keypair. It is vtafarm-api's OWN identity —
// generated by `make gen-keypair` and enrolled in a daemon's ACL with
// role=admin — not anything the daemon issued, so it is the same credential
// whichever host it authenticates against. See docs/vta-setup-design.md for
// the open question of how it reaches a user-supplied daemon's ACL.
type Factory struct {
	clientDid  string
	privKeyB64 string

	mu     sync.Mutex
	byBase map[string]*Client
}

// NewFactory returns nil when the keypair is unset, matching the old behaviour
// where an unconfigured DID_HOSTING_DID/PRIVATE_KEY disabled auto-upload
// altogether — callers already treat a nil client as "hosting not configured".
func NewFactory(clientDid, privKeyB64 string) *Factory {
	if clientDid == "" || privKeyB64 == "" {
		return nil
	}
	return &Factory{clientDid: clientDid, privKeyB64: privKeyB64, byBase: map[string]*Client{}}
}

// ClientDid is the DID that has to be present in a daemon's ACL for anything
// this factory builds to authenticate. Exposed so the platform stack's pipeline
// can enroll it offline while provisioning that daemon, rather than leaving an
// operator to do it by hand.
func (f *Factory) ClientDid() string {
	if f == nil {
		return ""
	}
	return f.clientDid
}

// For returns a Client for controlURL, reusing one already built for that URL.
//
// Caching is not just to save a round trip: New fetches the server's DID from
// /api/server-info, so an uncached call reaches the network on every upload,
// ACL write and teardown. Clients are keyed by URL and hold no per-session
// state, so sharing one is safe.
func (f *Factory) For(controlURL string) (*Client, error) {
	if f == nil {
		return nil, fmt.Errorf("DID hosting not configured (no client keypair)")
	}
	base := strings.TrimRight(controlURL, "/")
	if base == "" {
		return nil, fmt.Errorf("session has no DID hosting control URL")
	}

	f.mu.Lock()
	defer f.mu.Unlock()
	if c, ok := f.byBase[base]; ok {
		return c, nil
	}
	c, err := New(base, f.clientDid, f.privKeyB64)
	if err != nil {
		// Deliberately not cached: /api/server-info failing is usually a daemon
		// that is not up yet, and the next attempt should retry rather than
		// inherit the failure.
		return nil, err
	}
	f.byBase[base] = c
	return c, nil
}
