package didhosting

import (
	"fmt"
	"strings"
	"sync"
)

// Factory builds a Client for whichever DID-hosting control API a given session
// was provisioned against.
//
// The client used to be a startup singleton, built from DID_HOSTING_CONTROL_URL.
// That could not survive the control URL becoming a per-session value: the
// platform stack whose daemon default VTA-only sessions upload to does not exist
// on first boot, its URL changes when it is rebuilt, and a session torn down
// later has to be deleted from the daemon it was actually uploaded to rather
// than whatever is current.
//
// What stays global is the keypair. It is vtafarm-api's OWN identity —
// generated by `make gen-keypair` and enrolled in a daemon's ACL with
// role=admin — not anything the daemon issued, so it is the same credential
// whichever farm-managed host it authenticates against. External hosting
// never receives this credential; its owner publishes the log manually.
type Factory struct {
	clientDid  string
	privKeyB64 string

	mu     sync.Mutex
	byBase map[string]*Client
}

// NewFactory returns nil when the keypair is unset, matching the old behaviour
// where an unconfigured DID_HOSTING_DID/PRIVATE_KEY disabled auto-upload
// altogether — callers already treat a nil client as "hosting not configured".
func NewFactory(clientDid, privKeyB64 string) *Factory {
	if clientDid == "" || privKeyB64 == "" {
		return nil
	}
	return &Factory{clientDid: clientDid, privKeyB64: privKeyB64, byBase: map[string]*Client{}}
}

// ClientDid is the DID that has to be present in a daemon's ACL for anything
// this factory builds to authenticate. Exposed so the platform stack's pipeline
// can enroll it offline while provisioning that daemon, rather than leaving an
// operator to do it by hand.
func (f *Factory) ClientDid() string {
	if f == nil {
		return ""
	}
	return f.clientDid
}

// For returns a Client for controlURL, reusing one already built for that URL.
//
// The current control plane has no REST discovery or bearer-token surface.
// expectedServerDid is mandatory: it is the Trust Task recipient and the
// identity whose proof every response must carry.
func (f *Factory) For(controlURL, expectedServerDid string) (*Client, error) {
	if f == nil {
		return nil, fmt.Errorf("DID hosting not configured (no client keypair)")
	}
	base := strings.TrimRight(controlURL, "/")
	if base == "" {
		return nil, fmt.Errorf("session has no DID hosting control URL")
	}
	if expectedServerDid == "" {
		return nil, fmt.Errorf("session has no DID hosting service DID")
	}

	f.mu.Lock()
	defer f.mu.Unlock()
	if c, ok := f.byBase[base]; ok {
		return c, checkAudience(base, c.serverDid, expectedServerDid)
	}
	c, err := New(base, f.clientDid, f.privKeyB64, expectedServerDid)
	if err != nil {
		return nil, err
	}
	// Cached before the audience check, and the error returned alongside the
	// cached entry above: a mismatch says the CALLER's expectation is wrong for
	// this URL, not that the client is unusable. A later call carrying the right
	// expectation must hit the cache and succeed rather than re-fetching.
	f.byBase[base] = c
	return c, checkAudience(base, c.serverDid, expectedServerDid)
}

// checkAudience refuses to reuse a URL-pinned client for another service DID.
//
// A cached client remains pinned to the service DID it was constructed for.
// Sending a signed task to the same URL under a different recipient identity
// would otherwise break the request's audience binding.
func checkAudience(base, serverDid, expected string) error {
	if serverDid == expected {
		return nil
	}
	return fmt.Errorf("DID hosting client for %s is pinned to service DID %q, requested %q", base, serverDid, expected)
}
